# Generated by Django 5.2.5 on 2025-08-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('des_equipe_cadastro', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_funcionario', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula_funcionario', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nom_coordenador', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_lider', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_checklist', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_func_inspetor', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula_inspetor', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inspecao', models.DateField(blank=True, null=True)),
                ('tipo_formulario', models.CharField(blank=True, max_length=255, null=True)),
                ('sit_folha', models.CharField(blank=True, db_column='Sit. Folha', max_length=255, null=True)),
                ('possui_per', models.CharField(blank=True, db_column='Possui Per.?', max_length=255, null=True)),
                ('desc_funcao', models.CharField(blank=True, db_column='Desc.Funcao', max_length=255, null=True)),
                ('desc_depto', models.CharField(blank=True, db_column='Desc. Depto', max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('status_demissao', models.CharField(blank=True, db_column='Status Demissão', max_length=255, null=True)),
                ('desc_mun_l', models.CharField(blank=True, db_column='Desc. Mun. L', max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=255, null=True)),
                ('filial', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Inspeção SESMT',
                'verbose_name_plural': 'Inspeções SESMT',
            },
        ),
    ]
